### ISSUE TITLE
Settings pane does not scroll

### ISSUE THREAD

**Issue by jvasile** [zulip/zulip-desktop#557] opened 2018-09-05 17:14 UTC
I onboarded 40 new Zulip users at a conference this week.  This issue was reported by one of them, and I'm passing it on.  Thanks!

---

- **Operating System**:
  - [ ] Windows
  - [X] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Navigate to settings, click on notifications.  The right pane does not scroll (there is no visible scroll bar), and some settings are cut off by the bottom of the screen.
- **Relevant error messages and/or screenshots**:
None

**Comment by akashnimare** [comment] 2018-09-05 17:45
@jvasile I can't reproduce this on the latest version of the desktop app.

<img src="https://cl.ly/430896d790a2/download/Screen%20Recording%202018-09-05%20at%2011.13%20PM.gif"/>

Would be great if you can attach a screenshot/gif here. Also, make sure you're using the latest version which is [v2.3.6](https://github.com/zulip/zulip-electron/releases/tag/v2.3.6).

**Comment by jvasile** [comment] 2018-09-06 18:27
The user was indeed using the latest version, but shifted to a different device and uninstalled it.  Since it wasn't my report, I'm afraid I can't follow it up further than that.

**Comment by akashnimare** [comment] 2018-09-08 11:16
Closing since I can't reproduce this on my system. Feel free to reopen if you get more details on this.

**Closed as completed by akashnimare** 2018-09-08 11:16 UTC
Labels: investigate
