### ISSUE TITLE
Add a button for "Format as code"

### ISSUE THREAD

**Issue by johanneskastl** [zulip/zulip-desktop#1307] opened 2023-05-11 08:40 UTC
**Problem Description**

Underneath the text area there are three buttons for "bold", "italic" and "Insert link". There is none for "format as code".

**Proposed Solution**

An additional button for "Format as code". Maybe configurable.

**Additional context**

I know I can type backticks to format as code, but it would be great to have this as a button, too.

**Comment by andersk** [comment] 2023-09-30 06:10
Closing as duplicate of

- zulip/zulip#20302

**Closed as not planned by andersk** 2023-09-30 06:10 UTC
