### ISSUE TITLE
Mark as unread

### ISSUE THREAD

**Issue by hollov** [zulip/zulip-desktop#1072] opened 2021-01-28 15:23 UTC
Ability to mark messages as unread

**Comment by Elv1zz** [comment] 2021-04-01 20:17
That would be a really useful feature!
Alternatively the "Starred messages" category should have a message count badge, so I can star the messages at least and see that I have to come back to them later.

**Comment by timabbott** [comment] 2021-04-01 21:18
Thanks for the feedback!

This is a duplicate of https://github.com/zulip/zulip/issues/2676 -- I encourage you to upvote there.

That said, the "Starred messages" category does have an optional message count badge, in "display settings".  It's probably a mistake that isn't enabled by default for new users -- I'll take care of fixing that now since it's really quick.

**Closed as completed by timabbott** 2021-04-01 21:18 UTC
