### ISSUE TITLE
Dock icon on macOS unresponsive on the first click

### ISSUE THREAD

**Issue by stavros3006** [zulip/zulip-desktop#930] opened 2020-04-12 20:02 UTC
OS: macOS Catalina 10.15.4
Zulip v5.0.0

After the last update the dock icon does absolutely nothing when I click it for a first time. Normally it should bring the Zulip window into focus and on top of other windows. There is like a failed attempt at it doing it as the window shows up for less than a second but dissapears. I have to click the icon a second time for it to finally work.

So annoying.

**Comment by akashnimare** [comment] 2020-04-13 04:27
@stavros3006 can you check the status of "Always start Minimized" setting option?

**Comment by stavros3006** [comment] 2020-04-13 10:36
> @stavros3006 can you check the status of "Always start Minimized" setting option?

I didn't mean the first time as first time when I fire up the app. But while working in something else and I want to get Zulip into focus, on the first click of the icon it does nothing, and I have to cick it again for it to work. This was not an issue before the update to 5.0.0.

I always keep "Always start Minimized" to off.

**Comment by Alan-Solitar** [comment] 2020-04-14 02:06
OS: macOS Catalina 10.15.4
Zulip v5.0.0

I can confirm that this is happening for me as well, in addition to other other zulip users that I know.

After upgrading to zulip 5, zulip doesn't come up unless I click on it twice.  The same behavior occurs when I try to use the app switcher -- i.e., I have to perform the action twice.

**Comment by s1m0n0** [comment] 2020-04-14 05:27
OS: macOS 10.14.6
Zulip v5.0.0
For me it feels like, the first click on the tasklist icon minimices Zulip completely, a second click brings it back to front as it should on the first click. The window seems to get into front for a bit of a second and then hides. And i have the "start minimised" option turned off. Multiple persons in my company report the same behaviour on MacOS

**Comment by akashnimare** [comment] 2020-04-14 05:46
Is this the same as https://github.com/zulip/zulip-desktop/issues/914? If yes, we have fixed this issue and soon publish a new release.

**Comment by s1m0n0** [comment] 2020-04-14 06:04
Yes, should be a duplicate of #914 ... as per default resolved issues are hidden, stavros3006 might have overlooked it, same as me.

**Comment by stavros3006** [comment] 2020-04-14 06:42
> Yes, should be a duplicate of #914 ... as per default resolved issues are hidden, stavros3006 might have overlooked it, same as me.

Yeah, I totally did. @akashnimare feel free to treat it as duplicate entry.

Eagerly waiting for the update, the current behavior is frustrating as hell. :)

**Comment by akashnimare** [comment] 2020-04-14 14:54
Awesome! I'll update you folks, once we push a new release.

**Closed as completed** 2020-04-14 14:54 UTC
Labels: duplicate

**Comment by toph-allen** [comment] 2020-04-14 16:32
I hope you push the release soon — at least to the beta channel. 😅
