### ISSUE TITLE
Prevent Send message during uploading image

### ISSUE THREAD

**Issue by namse** [zulip/zulip-desktop#1233] opened 2022-09-03 07:02 UTC
**Problem Description**

If I send a message by pressing enter while uploading an image, a message will be sent during the image upload. The problem is that the image is still being uploaded, so the message `[Uploading image.png…]()` is sent.

**Proposed Solution**

I want you to block sending messages while images are being uploaded.

**Describe alternatives you've considered**

The best thing is that the original text of the message is automatically corrected when the image is uploaded. But it's too complicated.

**Additional context**

FYI, Github Issues and Pull Requests have similar issues.

**Comment by andersk** [comment] 2022-09-03 08:40
Duplicate of zulip/zulip#21135.

**Closed as not planned** 2022-09-03 08:40 UTC
