### ISSUE TITLE
Visual corruption / noise

### ISSUE THREAD

**Issue by nathanielvirgo** [zulip/zulip-desktop#1090] opened 2021-03-20 10:58 UTC
The Zulip client currently looks like this for me:

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/6964676/111867010-a88f1500-89b4-11eb-85fa-3e188c19649a.png">

This seems to be happening in all of the organisations that I'm subscribed to, but only for some streams and not others. Generally it seems not to happen if the stream only has one or two posts. Sometimes the whole left-hand column gets covered in that noise/snow pattern as well.

I've tried quitting and restarting the client, without success. I think this might have happened once or twice yesterday but then gone away again. It was fine earlier today, but now it seems to be happening pretty persistently. The Zulip client updated itself within the last few days, and I'm certain I never saw this before that.

I am running macOS 10.15.7 (Catalina) on a 2019 16-inch Macbook pro. I can't see a way to get the version of the Zulip client but I'm happy to update with that information if someone can tell me how.

**Comment by timabbott** [comment] 2021-03-22 03:19
Thanks for the report!  I think we've gotten a report of this before.  This symptom is almost certainly the result of a bug in the upstream version of Chromium used in the app; so it'll likely be fixed in our next release which will upgrade to newer Electron and thus Chromium (almost all of our Chromium bugs are fixed that way).

**Comment by timabbott** [comment] 2021-03-22 03:20
Closing as a duplicate of #1089.

**Closed as completed by timabbott** 2021-03-22 03:20 UTC
Labels: Type: Bug
