### ISSUE TITLE
Option to remove embedded link social preview per message (ala discord, telegram, ect.)

### ISSUE THREAD

**Issue by nuke-web3** [zulip/zulip-desktop#1366] opened 2024-04-17 23:41 UTC
**Problem Description**

By default it's usually great to get a social preview of links shared in a message, but not all are useful and some are distracting and unwanted. Some way to decide per message or even per link would be highly useful!

**Proposed Solution**

Discord has the option to remove the social preview card, although not ideal as it's all or nothing per message with multiple links:

![image](https://github.com/zulip/zulip-desktop/assets/35669742/5f2f3ab4-2367-46ea-a1a1-719e6f104932)

**Describe alternatives you've considered**

I think there is user and/or server settings to enable for messages globally, but nothing per message.

**Comment by alya** [comment] 2024-04-18 21:44
Thanks for the suggestion! Closing as a duplicate of https://github.com/zulip/zulip/issues/21766.

**Closed as not planned by alya** 2024-04-18 21:44 UTC
