### ISSUE TITLE
Menubar text colour illegible -- should respect system theme

### ISSUE THREAD

**Issue by skewty** [zulip/zulip-desktop#689] opened 2019-03-25 22:49 UTC
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
1. Install Ubuntu 19.04
2. Leave the theme as default `Yaru`
    * The menubar font color seems to be legible if `Yaru-dark` theme is selected.
3. Install Zulip 2.4.0 from PPA
- **Relevant error messages and/or screenshots**:
![Screenshot from 2019-03-25 15-40-56](https://user-images.githubusercontent.com/9087223/54958902-a7859300-4f14-11e9-9366-c8cec459ea66.png)

**Comment by akashnimare** [comment] 2019-03-26 14:58
@vsvipul, @kanishk98 can you folks reproduce this?

**Comment by kanishk98** [comment] 2019-03-26 15:06
Don't have immediate access to a Ubuntu system right now, but will check it out as soon as I can.

**Comment by vsvipul** [comment] 2019-03-26 15:08
Has been illegible for me as well, since the beginning.. I am on Ubuntu 18.04 . Though @skewty 's menu bar seems to be more illegible.
![Screenshot from 2019-03-26 20-34-36](https://user-images.githubusercontent.com/21038781/55008415-fc093b00-5006-11e9-8d84-d937ac80f050.png)

**Comment by kanishk98** [comment] 2019-03-26 15:19
Seems like a consistent problem. 
If we can figure out a way to change the colouring of the menu bar, I remember checking out [this module](https://www.npmjs.com/package/@jakejarrett/gtk-theme) for use in Zulip on Linux to determine the background colour of the theme and changing colours accordingly. Could this method be useful?

(I don't think Electron offers a native API to change the appearance of the title bar though, so that would have to be designed by us if we're choosing the CSS route)

**Comment by akashnimare** [comment] 2019-03-26 17:10
As far as I know, there is an API available for macOS to detect the theme but sadly no APIs for Linux/Windows. @skewty can you reproduce this issue in other apps which are based on electron?

**Comment by vsvipul** [comment] 2019-03-27 20:58
@akashnimare upgrading the electron version to 3.1.6 fixed this for me as shown. Can we bump up the version, should i send in a PR? 
![Screenshot from 2019-03-28 02-26-11](https://user-images.githubusercontent.com/21038781/55111775-20e1d900-5101-11e9-90c8-5cdc82123829.png)

P.S. this was fixed [here](https://github.com/electron/electron/issues/15823), and thus requires updating the electron version, as this might not be backported to current version 3.0.1, as far as i could find.

**Comment by akashnimare** [comment] 2019-03-29 10:18
> upgrading the electron version to 3.1.6 fixed this for me as shown. Can we bump up the version, should i send in a PR?

Okay, good to know this but hold on we have to test lots of stuff before upgrading to a new version of electron and we are also in the middle of a release.

**Comment by abhigyank** [comment] 2019-07-25 05:14
Should be fixed in the v3.1-beta release. @skewty Can you check?
Can be closed if works for everyone.

**Comment by skewty** [comment] 2019-07-25 15:21
Sorry, the company I work for purchased on-site Mattermost and we moved to that platform so I no longer have Zulip around for testing.

**Closed as completed** 2019-07-25 15:25 UTC
Labels: Status: Completed
