### ISSUE TITLE
Add topic autocompletion to the "Move message" feature

### ISSUE THREAD

**Issue by MartinX3** [zulip/zulip-desktop#1122] opened 2021-06-09 07:43 UTC
**Problem Description**

I need to write the exact topic name by myself if I want to move foreign messages to a different topic.

**Proposed Solution**

Autocompletion based on the written text.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by andersk** [comment] 2021-06-09 18:05
Closing as a duplicate of zulip/zulip#16368.

**Closed as completed by andersk** 2021-06-09 18:05 UTC
