### ISSUE TITLE
Visually distorted message area  on macOS

### ISSUE THREAD

**Issue by sportfloh** [zulip/zulip-desktop#1089] opened 2021-03-18 07:22 UTC
**Describe the bug**
After waking my Mac from sleep mode and start the Zulieb client again, the message area is completely visually distorted.

**To Reproduce**
Run the Zulip client, quit it, put the Mac to sleep mode, wake it again and start the Zulip client again

**Expected behavior**
A working GUI, no visually distorted message area.

**Screenshots**
![image](https://user-images.githubusercontent.com/588981/111587164-1e7f5a80-87c2-11eb-9b6b-cf7a41e3bbad.png)

**Desktop (please complete the following information):**
 - Operating System: 
macOS 11.2.3
 - Zulip Desktop Version:
5.6.0

**Additional context**
Rebooting fixes the problem.
https://techcommunity.microsoft.com/t5/microsoft-teams/pixelated-distortion-on-mac-teams-client/m-p/1279357
Microsoft Teams appears to have a similar problem. Maybe Electron is the common problem here.

**Comment by timabbott** [comment] 2021-03-18 19:30
Yeah, this is very likely a Chromium bug in the version used by the current Electron release we're using.  Might be fixed when we upgrade to Electron 12 -- bugs like this usually are.

**Comment by andersk** [comment] 2021-04-30 22:42
This is a bug in Apple’s AMD graphics driver. Closing as a duplicate of #1109, even though that was reported later, because the details are there.

**Closed as completed by andersk** 2021-04-30 22:42 UTC
Labels: Type: Bug
