### ISSUE TITLE
Certificate error 

### ISSUE THREAD

**Issue by ali-yahyaoui** [zulip/zulip-desktop#1141] opened 2021-07-29 08:54 UTC
This pop-up is shown when opening some streams on Zulip Desktop.
PS: We have a valid commercial SSL certificate for our domain.
![image](https://user-images.githubusercontent.com/60253677/127462272-cbf3e02e-a3cb-4a10-84fc-6effb6f63346.png)

**Comment by timabbott** [comment] 2021-08-03 20:24
@ali-yahyaoui are you seeing this in the desktop app?  The problem is Zulip is trying to load a link preview of another domain that has an invalid certificate, and the desktop app error handling for this doesn't work.

**Comment by andersk** [comment] 2021-08-03 20:26
Closing as duplicate of #1119.

**Closed as completed by andersk** 2021-08-03 20:26 UTC

**Comment by ali-yahyaoui** [comment] 2021-08-04 08:10
@timabbott  Yes in Zulip Desktop v5.8.1, Okay thanks well understood.
