### ISSUE TITLE
Zulip not starting up in Windows

### ISSUE THREAD

**Issue by parthi2929** [zulip/zulip-desktop#851] opened 2019-12-11 09:56 UTC
---

- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Simply install latesst version v4.0.0, ensure in settings startup at login enabled  and restart
- **Relevant error messages and/or screenshots**:
The zulip app is not started on startup (not on main desktop nor in system tray)

**Comment by akashnimare** [comment] 2019-12-11 10:21
@parthi2929 have you turned on the following setting-

![image](https://user-images.githubusercontent.com/2263909/70613058-0bc8be00-1c2e-11ea-81cd-7139f4d44c6a.png)

**Comment by parthi2929** [comment] 2019-12-12 07:41
yes, of course. These are set by default as well.

**Comment by akashnimare** [comment] 2019-12-12 07:43
Okay. Let me check. Are you on Windows 10? Can you tell me the build version etc?

**Comment by parthi2929** [comment] 2019-12-12 07:45
yes, please check below. 

![image](https://user-images.githubusercontent.com/11896263/70692483-76870180-1ce1-11ea-916b-e4bc838fdc66.png)

**Comment by parthi2929** [comment] 2019-12-13 05:51
any update?

**Comment by akashnimare** [comment] 2019-12-14 09:23
@parthi2929 tested this on my machine, works as expected. Can you toggle the startup setting again and see if it works?

**Comment by akashnimare** [comment] 2019-12-14 09:25
Can you check if it's registered properly -

```
\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
```

**Comment by sulian** [comment] 2019-12-17 15:40
Same problem here (**Windows 10 Pro 1903 18362.535**), and no entry in registry.
Need to add manual entry by `shell:startup`

**Comment by akashnimare** [comment] 2019-12-17 19:24
@vsvipul, @kanishk98 can you guys reproduce this?

**Comment by parthi2929** [comment] 2019-12-20 06:19
This is what my Run area in registry looks like

![image](https://user-images.githubusercontent.com/11896263/71234394-a60bbe80-231e-11ea-9ac9-eb8a8734fc5d.png)

Should we add Zulip here? If so, how and what?

**Comment by parthi2929** [comment] 2019-12-31 15:41
Hello? Please update as we intend to use this in our company.

**Comment by akashnimare** [comment] 2019-12-31 18:11
@parthi2929 I'll test this on some other windows machines as well since it's working for me as expected. 

we are currently using our own mechanism for auto-start. I'll dig deeper into this and if our mechanism doesn't work we'll go with the official electron API but we'll definitely fix this one way or another.

**Comment by parthi2929** [comment] 2020-01-01 05:29
Thank you @akashnimare  In mean time, can we have any work around? Like tweaking registry with a manual addition etc?

**Comment by akashnimare** [comment] 2020-01-02 09:54
@parthi2929 you can add `zulip` manually to the registry and it should work. Just right-click in that area and add a new key + add the value (i.e. the path of the zulip app).

Here are the full-steps -

https://cl.ly/354fcad9ac19

Let me know if it works.

**Comment by vsvipul** [comment] 2020-01-10 18:20
@parthi2929 Can you test this and see if works for your system ? https://github.com/zulip/zulip-desktop/pull/859

**Comment by parthi2929** [comment] 2020-01-11 12:00
@vsvipul I did not try as @akashnimare suggestion worked. Hope this fix is included (path was different, not Program Files) as we would need this to be automatic for all team members. 

Actual path:  
```
C:\Users\%username%\AppData\Local\Programs\Zulip\
```

**Comment by akashnimare** [comment] 2020-01-11 18:34
Awesome. I'll update you once we push a proper fix for the same.

**Comment by parthi2929** [comment] 2020-01-27 02:45
Any update? It would be tedious for us to fix register in each and ever zulip team member PC.

**Comment by akashnimare** [comment] 2020-01-27 07:22
@parthi2929 yeah, we have pushed a fix in https://github.com/zulip/zulip-desktop/pull/859. Just need to test the same on Windows.

**Closed as completed** 2020-01-28 06:56 UTC
Labels: Type: Bug, in progress, investigate

**Comment by parthi2929** [comment] 2020-01-28 13:04
@akashnimare great, I could not find when its planned. It could be available already in any beta?

**Comment by akashnimare** [comment] 2020-01-28 18:37
@parthi2929 I'll update here once we ship this to prod.

**Comment by akashnimare** [comment] 2020-05-27 08:10
@parthi2929 does this work for you in the latest release which is v5.2.0?

https://zulipchat.com/apps

**Comment by parthi2929** [comment] 2020-05-28 11:20
yes, after I update it seems to be working, (but also I did not try removing the reg edit, so not sure if the zulip during startup is due to new update or the reg fix)
