### ISSUE TITLE
The add button doesn't work when adding a new server.

### ISSUE THREAD

**Issue by adambirds** [zulip/zulip-desktop#318] opened 2017-10-14 22:40 UTC
The add button doesn't work when adding a new server on the windows app.

OS is Windows 10.

```
Zulip 1.5.0
Electron 1.6.14
win32 x64 10.0.15063
```

**Comment by cedricium** [comment] 2017-10-14 23:02
Hey @adambirds, just to clarify: are you talking about the '+' button in the sidebar or the 'Create a new organization' link found in Settings under the 'General' category?

**Comment by adambirds** [comment] 2017-10-14 23:07
Hi @cedricium The add button in the image below is the issue.

![image](https://user-images.githubusercontent.com/13500254/31580038-ab13722a-b13c-11e7-9c1b-194d3a883797.png)

**Comment by cedricium** [comment] 2017-10-14 23:15
Gotcha. I have a Win10 machine, I'll go ahead and look into this for you.

**Comment by adambirds** [comment] 2017-10-14 23:31
Here is the Win10 version build number in case it makes a difference:
![image](https://user-images.githubusercontent.com/13500254/31580170-1c6c4bba-b140-11e7-90c4-08a2a213c88a.png)

**Comment by adambirds** [comment] 2017-10-16 05:42
@cedricium any look on this yet?

**Comment by cedricium** [comment] 2017-10-16 05:52
@adambirds sorry about that, will debug right now. And just to try to reproduce the issue correctly, how did you download the app?

**Comment by adambirds** [comment] 2017-10-16 05:59
@cedricium I downloaded it from zulipchat.com on the website there.

**Comment by cedricium** [comment] 2017-10-16 06:22
@adambirds unfortunately I wasn't able to reproduce the issue. If you haven't already tried uninstalling then installing the app, I would say try going to `Settings > General > Reset App Data` then restart the app. Try adding the server again and if that doesn't work, then go ahead and uninstall then install the app.

@akashnimare maybe you can try reproducing. My system settings are:
```
Zulip 1.5.0
Electron 1.6.14
win32 x64 10.0.14393
Windows Version 1607 (OS Build 14393.1715)
```
I tried several ways to repro:
- downloading the `Zulip-Web-Setup-1.5.0.exe` from https://github.com/zulip/zulip-electron/releases/tag/v1.5.0
- downloading the app via https://www.zulipchat.com/apps/windows (which downloads v1.4.0), then upgrading to v1.5.0 after being prompted for a new version

**Comment by akashnimare** [comment] 2017-10-16 15:47
@adambirds please try again. I can add your server.

![image](https://user-images.githubusercontent.com/2263909/31621468-67a6f9cc-b2b7-11e7-813b-a8f95544f154.png)

**Comment by timabbott** [comment] 2017-10-16 16:15
It seems unlikely to me that whatever @adambirds is experiencing won't affect other users.

@adambirds can you check the Developer tools when you're experiencing it not working?  I'm wondering if there's an exception there that might give a clue as to what's happening here.

**Comment by akashnimare** [comment] 2017-10-16 16:23
I was not able to add this server yesterday (no errors in console) but as of now it's working fine. I'm guessing the error has more to do with the server configurations.

**Comment by adambirds** [comment] 2017-10-16 19:50
@timabbott @akashnimare works fine for me now, and no errors in Dev tools. Possibly my server maybe, it was having a few issues yesterday, so possibly that. Tested on a few different clients this time and seems fine.

**Comment by akashnimare** [comment] 2017-10-16 20:18
Closing. Feel free to reopen if this happens again.

**Closed as completed by akashnimare** 2017-10-16 20:18 UTC
Labels: investigate

**Comment by timabbott** [comment] 2017-10-17 05:34
@akashnimare do we provide feedback when the server gives a 500 error or isn't reachable when trying to add it?  I feel like this is something where the actual problem here is we need a little loading indicator + error message display "we could not connect to this server" for this UI widget; I imagine if we'd had that, I suspect @adambirds would have been confident the problem wasn't a bug in the app.  What do you think?

**Comment by adambirds** [comment] 2017-10-17 05:41
Yeah, some feedback on if it could connect to the server would be great! At least then you know to take a look at the log files on both the client and server to see why it couldn't connect.

**Comment by timabbott** [comment] 2017-10-17 05:45
Cool. @akashnimare should we make a new issue for doing that to help keep things clean?
