### ISSUE TITLE
Weird rendering when waking up from sleep on OSX

### ISSUE THREAD

**Issue by edgarcosta** [zulip/zulip-desktop#1129] opened 2021-07-02 13:54 UTC
**Describe the bug**

The electron app has some rendering issues with some blocks when waking up from sleep on OSX.
Restarting the app doesn't solve the issue.

**To Reproduce**

I can't reproduce it on demand, but here are the common factors that I have observed:
- waking up from sleep on OSX
- an external monitor, 
- scrollable block?
- and some bad luck.

**Expected behavior**

The windows to render properly.

**Screenshots**

Here is an example showing that this is down to the electron app, as even the developer tools doesn't render properly.
<img width="927" alt="developer tools" src="https://user-images.githubusercontent.com/322822/124278812-b5271b80-db14-11eb-9988-0b6c8469fa6d.png">

The size of the block seems to play some role:
![zulip](https://user-images.githubusercontent.com/322822/124284445-03d7b400-db1b-11eb-83d2-7e0da4143eca.gif)

**Desktop (please complete the following information):**

- Operating System:
macOS 10.15.7

- Zulip Desktop Version:
5.7.0

**Additional context**

As you can see in my screenshot, even the developer tools doesn't render properly. Thus, why I believe this is an issue with the GPU settings of electron.

**Comment by timabbott** [comment] 2021-07-13 16:03
@edgarcosta can you try upgrading macOS?  In the past, failure modes like this has been traced to bugs in the macOS graphics drivers that have been fixed in more recent macOS releases.

**Comment by timabbott** [comment] 2021-07-13 16:03
See e.g. https://github.com/zulip/zulip-desktop/issues/1109#issuecomment-872639130.

**Comment by andersk** [comment] 2021-07-13 17:44
Closing as duplicate of #1109.

**Closed as completed by andersk** 2021-07-13 17:44 UTC
