### ISSUE TITLE
Reconnection issue on startup

### ISSUE THREAD

**Issue by flaviozluca** [zulip/zulip-desktop#1225] opened 2022-07-08 15:54 UTC
Friends,

Sorry, I didn't know there was a specific repo for the desktop app, so I had opened the issue here, originally: https://github.com/zulip/zulip/issues/22243

Sometimes Zulip desktop app stalls on startup, keeps trying to load forever. 5.9.3 desktop app on Win 11.

Video attached. Over 30 min later, still it wont reconnect. I close Zulip, reopen it again, it immediatly connects.

https://user-images.githubusercontent.com/44004645/178027400-7c06f722-a163-4dd0-ba54-140f15a49e14.mp4

In the link I sent, another user mentioned the same issue.

Thanks.
[stalls.zip](https://github.com/zulip/zulip-desktop/files/9073385/stalls.zip)

**Comment by vrozkovec** [comment] 2022-09-24 15:32
Related / duplicate of: https://github.com/zulip/zulip-desktop/issues/1220

**Comment by andersk** [comment] 2023-02-07 06:20
Zulip Desktop 5.9.5 fixes a bug where the app would freeze in this case. It should now display the network error page and otherwise continue working normally.

**Closed as completed by andersk** 2023-02-07 06:20 UTC
