### ISSUE TITLE
Organisation tabs crashing and becoming grey

### ISSUE THREAD

**Issue by nathanielvirgo** [zulip/zulip-desktop#1267] opened 2023-01-21 14:04 UTC
**Describe the bug**

I'm a member of several different Zulip organisations, which appear as icons on the left of the app. (These are what I'm calling "tabs"). Recently, every now and then, one of the tabs stops working. If I switch to it all I see is a grey screen.

When this happens I can't reload the tab by pressing CMD-R. As far as I can tell the only way I can get it working again is to quit and re-open the app.

The red icons showing the number of messages stop updating when this happens - they stay frozen at whatever number they showed when the tab crashed.

**To Reproduce**

I don't have a way to reproduce it, it just happens once every day or two. So far it's never been the frontmost tab that stops working - it's always one of the organisations I'm not currently viewing.

**Screenshots**

<img width="980" alt="image" src="https://user-images.githubusercontent.com/6964676/213870289-0cffae7c-8876-4557-b397-a1d3bdc4e895.png">

**Desktop (please complete the following information):**

- Operating System: macOS 12.6.1

- Zulip Desktop Version: 5.9.4
 

**Additional context**

I'm used to the tabs crashing every now and then, but that used to give me an error message (I can't remember what it said exactly) and I could re-load the tab using CMD-R, so it wasn't a big deal. I don't know if this is a new manifestation of the same problem or something new.

**Comment by nathanielvirgo** [comment] 2023-01-22 04:24
One more piece of information: it seems that keyboard shortcuts don't work when viewing a tab that's in this state. E.g. I can't use CMD-Q to quit the app, or use CMD-1 etc. to switch to another tab.

This has happened more than once today, by the way - it's making the app very awkward to use, since I have to keep quitting and restarting all the time.

**Comment by orilahav** [comment] 2023-01-24 20:15
Similar issue for me (on macOS 12.6.2). 
These crashes happen quite frequently.
(I think it started with 5.9.4. Will try to downgrade if possible.)

**Comment by goens** [comment] 2023-01-27 12:46
Same here on macOS 12.1 (arm), also started when upgrading to 5.9.4.

**Comment by nathanielvirgo** [comment] 2023-02-06 01:49
Did anyone figure out a way to downgrade to a working version?

And also is there some chance of any feedback about this from Zulip devs? I guess you're probably all volunteers, but still, I'm pretty heavily invested in Zulip as a research/collaboration tool at this point, and it would help a lot to know that this is on your radar in some way.

**Comment by andersk** [comment] 2023-02-06 20:44
Previous releases are available on our [releases page](https://github.com/zulip/zulip-desktop/releases), although we always recommend the latest release for security reasons.

Yes, this is on our radar, but it’s difficult to debug since (a) it’s a crash in upstream Electron and Chromium code and (b) we don’t have a reproduction recipe that we would need to report it upstream. The best we can do is keep upgrading Electron and hoping the upgrades introduce fewer new bugs than they fix.

I am working on enabling additional Chromium sandboxing features which, along with improved security, might make it easier to recover from crashes (but no promises there since the exact nature of this crash remains mysterious).

**Comment by orilahav** [comment] 2023-02-07 05:03
See also:
https://chat.zulip.org/#narrow/stream/16-desktop/topic/grey.20screen

**Comment by andersk** [comment] 2023-02-07 06:12
I’ve released Zulip Desktop 5.9.5, with Electron 22.2.0 and Chromium sandboxing of the renderer process. I don’t know whether this will fix the crash—try it out and let me know if it works for you.

**Comment by nathanielvirgo** [comment] 2023-02-09 07:24
It's been a couple of days since the update and there haven't been any crashes, so I think it's pretty clear that this has fixed it. Thank you so much!

**Comment by andersk** [comment] 2023-02-11 01:05
Thanks. I’ll tentatively close this as fixed (possibly by electron/electron#36567 and/or #1271), but please speak up if you see this again in 5.9.5 or newer.

**Closed as completed by andersk** 2023-02-11 01:05 UTC
