### ISSUE TITLE
Right click context menu closes instantly v5.3.0

### ISSUE THREAD

**Issue by GertBurger** [zulip/zulip-desktop#991] opened 2020-06-26 16:03 UTC
**Describe the bug**
Right click context menu closes instantly in message editor

**To Reproduce**
Right click in message editor

**Expected behavior**
Context menu should stay open 

**Screenshots**
![Peek 2020-06-26 17-58](https://user-images.githubusercontent.com/23653/85877200-136d4000-b7d7-11ea-8a2e-584ff4794372.gif)

**Desktop (please complete the following information):**
 - Operating System: 
 Ubuntu 18.04 64-bit

 - Zulip Desktop Version:
Started in 5.3.0, was fine in 5.2.0

**Additional context**
Installed via `snap install zulip`

**Comment by abhigyank** [comment] 2020-06-27 04:47
@punchagan Do you see this when you install using `snap` ?

**Comment by punchagan** [comment] 2020-06-27 06:13
Yes, I can reproduce this

**Comment by abhigyank** [comment] 2020-06-27 09:32
Okay, I can reproduce this after installing through `snap`. Works correctly in deb and AppImage. 

I can reproduce in the server webview (not consistently though, works sometimes), but not in other parts of the app like settings or add new server. I find this very weird.

**Comment by abhigyank** [comment] 2020-06-27 09:38
@GertBurger  @punchagan  Does restarting the app make it go away? I restarted my app (installed via snap) and unable to reproduce anymore.

**Comment by punchagan** [comment] 2020-06-27 09:59
Yeah, that happened for me too.

**Comment by GertBurger** [comment] 2020-06-27 10:40
That works, the context menu looks a bit odd but its functional.

Ta for your time on such a minor issue...

**Comment by abhigyank** [comment] 2020-06-27 10:42
> the context menu looks a bit odd but its functional.

Yes! It's fixed in the master, will be there in the next release.

**Comment by GertBurger** [comment] 2021-01-12 07:02
This is still a problem in 5.5.0

**Comment by adambirds** [comment] 2021-03-23 01:20
I'm also getting these issues, although it is intermittently.

**Comment by adambirds** [comment] 2021-03-23 01:20
And for context, not installed via snap and using on Windows 10.

**Comment by jerbasco1** [comment] 2021-05-21 17:34
I am having this issue intermittently as well. Windows 10 desktop client 5.7.0
Quit and re-open fixes it temporarily for me as well.

**Comment by GertBurger** [comment] 2021-05-24 06:02
Still a problem on Linux with 5.7.0 appimage.

**Comment by nooblag** [comment] 2021-06-30 15:30
I can also confirm the issue on Linux AppImage 5.7.0 on Linux Mint 20. I only get this glitch with chat.zulip.org (Version 5.0-dev-953-g99add14a5f), other Zulip Cloud instances seem okay (Version 5.0-dev-432-ge9ad1d00e4).

**Comment by GertBurger** [comment] 2021-07-05 06:36
For me it occurs on all instances tested so far, our own and the public one. It just takes a while to trigger.

**Closed as completed** 2021-10-09 01:13 UTC
Labels: investigate

**Comment by cizra** [comment] 2021-12-28 17:01
Is it actually fixed? I'm on 5.8.1 and it still happens.

**Comment by andersk** [comment] 2021-12-28 19:38
The fix is in Git `main`; it will be part of the next release.
