### ISSUE TITLE
Hidden pop-up is focused  in background on context switch

### ISSUE THREAD

**Issue by jamak** [zulip/zulip-desktop#158] opened 2017-05-26 23:54 UTC
on OSX,  on ⌘-tab switch back into the electron app, a hidden window (I assume the settings pop-up?) is focused. In the browser, when you return to the tab, the home stream is focused. This is as of f6358a0 .

To reproduce:
* open zulip-electron
* switch to another application
* switch back to zulip-electron

**Comment by akashnimare** [comment] 2017-05-28 06:23
I'm not able to reproduce this. Can you please make a gif/video of the same?

**Comment by akashnimare** [comment] 2017-05-28 08:32
@SimplyAhmazing pushed a fix in https://github.com/zulip/zulip-electron/commit/deafa315dffb10c364556650e6f352c8f5621224. Can you verify if it works for you?

**Comment by jamak** [comment] 2017-05-28 12:05
Yep, works for me. Nice job, @SimplyAhmazing!

**Closed as completed** 2017-05-28 13:54 UTC
