### ISSUE TITLE
Remove CMD/CTRL-L logout shortcut

### ISSUE THREAD

**Issue by alya** [zulip/zulip-desktop#1134] opened 2021-07-20 06:09 UTC
**Problem Description**

The desktop app has a CMD/CTRL-L shortcut for logging out. This is quite close to the CMD/CTRL-SHIFT-L shortcut for inserting a named link, making it easy to accidentally log oneself out (which I do with some frequency!).

**Proposed Solution**

The simplest solution is to remove this log out shortcut. In general, one shouldn't need to log out very often, so having users do it through the menus seems reasonable.

**Comment by andersk** [comment] 2021-07-20 06:17
Closing as duplicate of #1115, already fixed in Git by 1d30c83f7aa1c2b55d2bdb26e51fd0211d2a820e.

**Closed as completed by andersk** 2021-07-20 06:17 UTC

**Comment by alya** [comment] 2021-07-20 06:53
Oh, oops, sorry I didn't check! I guess @timabbott  forgot that we already had an issue for it when I mentioned it. :)
