### ISSUE TITLE
Visual notifications shown when "Do not disturb" is turned on

### ISSUE THREAD

**Issue by alya** [zulip/zulip-desktop#1299] opened 2023-04-11 14:25 UTC
As [reported on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/visual.20notification.20on.20despite.20setting.20.22Do.20not.20disturb.22/near/1525046), visual desktop notifications are still shown when the "Do not disturb" option is turned on. We should fix this.

@_**Anders Kaseorg|699** [said](https://chat.zulip.org/#narrow/stream/9-issues/topic/visual.20notification.20on.20despite.20setting.20.22Do.20not.20disturb.22/near/1536788):

> This seems to have been broken since v5.0.0 (specifically [v5.0.0~6](https://github.com/zulip/zulip-desktop/commit/9d4093b3d8647e1896fc2c0a29c65ff46477b55b)).

**Comment by cyrilchukwuebuka** [comment] 2023-04-12 09:33
@alya I would love to be assigned this issue
I'm currently examining the bug for a fix

**Comment by alya** [comment] 2023-04-13 04:01
Sure! Please post a comment describing your proposed approach when you're ready. You can have the issue assigned to you after you [have a rough plan](https://zulip.readthedocs.io/en/latest/overview/contributing.html#picking-an-issue-to-work-on) for how to address it. Thanks!

**Comment by enesonus** [comment] 2023-04-13 22:24
@alya I think that the problem is we do not sync inapp DND mode state with the machine's DND mode state. As far as I understood, we only look at in-app dnd mode to send visual or voice notifications. Electron documentation for [notifications](https://www.electronjs.org/docs/latest/tutorial/notifications#do-not-disturb--session-state) suggests using [macos-notification-state](https://github.com/felixrieseberg/macos-notification-state) package to check if the app is allowed to send a notification for macOS. I could not find this package in zulip-desktop repo so concluded that we do not have a mechanism for checking macOS machines' DND mode.

For linux I could not find a promising fix but this [thread](https://askubuntu.com/questions/1311428/20-10-getting-notifications-despite-do-not-disturb) seems useful and also It might be a good idea to look at VSCode's notification implementation for linux based machines.

If you could assign me to this issue I would be happy to work on it!

**Comment by cyrilchukwuebuka** [comment] 2023-04-18 01:14
Referencing what @enesonus said, the application does not have a native check and integration with OS for notification state as documented on [Electron](https://www.electronjs.org/docs/latest/tutorial/notifications) such as in Windows, using the [windows-notification-state](https://github.com/felixrieseberg/windows-notification-state) and other OS and their packages, though it's secondary to the current bug as basically from the knowledge I could garner Zulip desktop makes use of browser Window Notification.

This current bug could be related to [#4174](https://github.com/electron/electron/issues/4174) issue with [PR(#4223)](https://github.com/electron/electron/pull/4223) on the Electron repository because Zulip desktop makes use of webview to display web contents such as a Zulip chat web page and as such is possible, the notification could as well come from the webview.
In this technique, the expedient approach is to implement [ses.setPermissionRequestHandler(handler)](https://www.electronjs.org/docs/latest/api/session#sessetpermissionrequesthandlerhandler) for the notification and media(sound) which would restrict audio and visual notification display from a webview webcontent when DND is enabled/disabled or in specific settings options such as "mute all sounds from Zulip" and "show desktop notifications"



Alternatively, disabling notifications both the visual and sound notifications could also be achieved dynamically using a similar technique on the webview instance showNotificationSettings method which calls ipcRender.on("show-notification-settings"),

<img width="367" alt="Webview show notification" src="https://user-images.githubusercontent.com/41521163/232641034-8dd5ff87-eb21-4137-82a7-a622f662eb5b.PNG">

<img width="564" alt="preload ipcRenderer" src="https://user-images.githubusercontent.com/41521163/232642225-5d2d3f3b-e39c-4d8e-bd5e-cb6f8da471ce.PNG">

<img width="554" alt="disable noification" src="https://user-images.githubusercontent.com/41521163/232642596-d02ac074-14c1-4137-88cd-1c4d8a06ce94.PNG">


So once the notification settings come up, we can disable desktop notifications for visual and/or audio. The only drawback to this method is that it only applies to the current displayed webview. Likewise for the enabling option.


@andersk, I would be glad if you could review the feasibility of these solutions as outlined above in order for @alya to assign the issue to me

**Closed as completed** 2023-04-18 20:13 UTC
Labels: Type: Bug, help wanted
