### ISSUE TITLE
Indicate legacy/unmaintaned state on latest zulip-electron release

### ISSUE THREAD

**Issue by schrej** [zulip/zulip-desktop#880] opened 2020-03-02 09:04 UTC
We've just noticed the old zulip-electron repository still exists.
The [releases page](https://github.com/zulip/zulip-electron/releases) still contains the last release from that repository and it's marked as "latest release". Since zulip-electron is superseded by zulip-desktop by now, I'd recommend to add a notice telling people to switch to the new client, as it's not that obvious that zulip-electron doesn't receive updates anymore and has led to confusion about the latest version in our case.

In addition it would be good if the "check for updates" dialog wouldn't say that v2 is still the latest version, but I assume that might require too much effort to fix.

**Comment by timabbott** [comment] 2020-03-02 21:46
The situation is kind of a mess, and some of the things we'd like to here are not technically possible.  The root cause of this is a bug in v2.3.82's auto-updater software (which is done via a the third-party dependency, `electron-builder`) which made the app crash on startup if a newer version was added to the "releases" page.  that project does claim it's frozen in the "description" at the top, but not in the README, sigh; we can add that.  

This is why we've added a change to warn users running v2.3.82 that auto-update is broken on that version and they need to upgrade manually; which really should have happened a long time ago.  It's available on zulipchat.com and the `2.1.x` stable release branch for self-hosted servers.  (Will be in release 2.1.3 as soon as we can release that).

What I'm tempted to do at this point is just take down the `zulip-electron` repository (marking it as archived) and have v2.3.82 crash on startup if need be, since there's no good reason for anyone to be running that version in any case.  But we should probably test our options a bit before doing that.

I'll discuss with @akashnimare.

**Comment by timabbott** [comment] 2020-03-02 21:52
I at least marked zulip-electron as a dead repository very clearly on its README page, thanks for the report.  I expect we'll delete the repository soon as well; zulipchat.com logs show that already a significant large majority of clients previously on v2.3.82 have upgraded manually, so whatever negative impact of having that app version crash on startup is rapidly falling.

**Comment by schrej** [comment] 2020-03-03 15:51
>  that project does claim it's frozen in the "description" at the top, but not in the README, sigh; we can add that.

On the releases page that's not visible. If you switch to releases quickly without reading the description (because why would you when you've been on the repo before), the releases still lists the latest release as "stable". If it's possible to change the description of that release, it would help to add a note there as well that it's not actually the latest version. Unless you delete the whole repository of course.

Instead of deleting it you could also archive it, which adds a much more visible banner at the top, but still keeps it available as read-only.

I don't know whether the electron/desktop client sends it's version in the user agent (or something else), but that could be used to show a warning on the webapp to upgrade to the latest version, just as an idea on how to tackle that.

**Comment by timabbott** [comment] 2020-03-03 19:23
> I don't know whether the electron/desktop client sends it's version in the user agent (or something else), but that could be used to show a warning on the webapp to upgrade to the latest version, just as an idea on how to tackle that.

We do this as of Friday.

**Comment by abhigyank** [comment] 2020-06-02 08:17
Can we close this issue? We do show the warning now and the app doesn't work on older versions.

**Comment by schrej** [comment] 2020-06-02 08:38
The zulip-electron repository should still be archived in my opinion.

**Comment by timabbott** [comment] 2020-06-02 19:57
Yes, agreed, I just took care of that.  Our analytics show essentially no clients are still running the v2.3.82 version, thanks for the reminder!

**Closed as completed by timabbott** 2020-06-02 19:57 UTC
