### ISSUE TITLE
No hover info on emojis or reactions

### ISSUE THREAD

**Issue by uri** [zulip/zulip-desktop#224] opened 2017-07-19 21:19 UTC
- `macOS Sierra 10.12.1`
- Add a reaction and hover over it.
- Hover should show who reacted and the emoji name like it does in the browser.

**Comment by timabbott** [comment] 2017-07-19 21:28
Interesting, thanks for the report!

**Comment by uri** [comment] 2017-07-19 21:47
This seems to be fixed in the 1.2 beta. Was using v0.5.10

**Comment by akashnimare** [comment] 2017-07-20 09:32
@uri can you reproduce this on v1.2.0-beta?

**Comment by akashnimare** [comment] 2017-07-25 18:03
Closing it as I can't reproduce this on v0.5.10/v1.2.0-beta.

v0.5.10 - 

![image](https://user-images.githubusercontent.com/2263909/28586500-b84fc8ac-7191-11e7-9b6d-9afe4271c8b6.png)

**Closed as completed by akashnimare** 2017-07-25 18:03 UTC
Labels: Type: Bug, Priority: Medium
