### ISSUE TITLE
Too much maths causes issues sending

### ISSUE THREAD

**Issue by nathanielvirgo** [zulip/zulip-desktop#1347] opened 2023-12-06 10:05 UTC
**Describe the bug**

If you type too much math into a post it causes problems sending the message. It appears as if the message has been sent but it has not. This can lead to confusion about whether the message has been sent, because of the issue in zulip/zulip#29097, and it can also lead to the message being lost entirely if you fail to notice that it wasn't sent.

**To Reproduce**

1) Compose a message (e.g. a personal message to yourself) with a large number of equations in it, e.g. like this:

````
```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```

```math
H = -\sum_{x\in X} p(x) \log p(x)
```
````
(if reproducing doesn't work, just paste in more copies of the equation. It's intermittent but becomes more likely the more equations there are.)

2) hit the send button, without viewing the preview first. Now it looks as if the message has been sent and everything is fine:

<img width="869" alt="image" src="https://github.com/zulip/zulip-desktop/assets/6964676/741891fa-d79b-455e-a3a3-7acbb52b09f3">

3) click on "SHOW MORE". Now we reach this state:

<img width="856" alt="image" src="https://github.com/zulip/zulip-desktop/assets/6964676/7fd87871-6d56-476a-b950-b6fb0d3c19f5">

Notice the red icons in the top right - it has not been sent, even though it seemed like it had. Mousing over the spinning wheel in the top right yields the message "Your message is taking longer than expected to be sent. Sending..."

The options are to retry or cancel the message. Hitting retry never works, it just stays in the same state. Cancel doesn't drop back to the editor but does seem to save the message in drafts, at least some of the time. (I think the cancel button should return to the editor, but that's a separate issue, see zulip/zulip#29097)

**Additional notes**

If you type too many equations and try to preview the message it says "failed to generate preview". In that case I can tell what the problem is and usually edit the message in an external editor to split it into smaller parts. But sometimes I'm just on a roll and don't think to preview the message before sending, and in that case I run the risk of losing my message because of this issue. 

My example might seem like an extreme case, but this does happen fairly often when typing messages about maths. A message with a lot of small inline equations can easily be enough to trigger the issue.

**Expected behavior**

I expect the message to be successfully posted, or if not, I expect an error message explaining why it couldn't be posted, and an opportunity to edit the message to address the issue.

**Screenshots**

see above.

**Desktop (please complete the following information):**

- Operating System: MacOS Monterey 12.6.5

- Zulip Desktop Version:
 v5.10.2

**Additional context**

Bug zulip/zulip#29097 is a closely related issue. When I wrote that one I didn't know what was causing this state. That report is about not having any way to recover the message once such a state is entered, while the current report is about this "sending..." problem itself and how to reproduce it.

**Comment by andersk** [comment] 2023-12-11 07:52
Closing as duplicate of zulip/zulip#17425.

**Closed as not planned** 2023-12-11 07:52 UTC
Labels: duplicate

**Comment by nathanielvirgo** [comment] 2023-12-11 09:58
fair enough with the duplicate - I wasn't sure whether to edit that one or add a new one since they were similar. But does 'not planned' mean this isn't considered a bug?

**Comment by nathanielvirgo** [comment] 2023-12-11 09:59
I'm not the only person who gets caught by this. Another user on the category theory zulip recently posted this:

> I had begun writing a long response, but everything got screwed up because one of the comments was "too long" for this stupid zulip to handle -- and then everything got fouled up.
>
> If I have the time and energy, then I'll reconstruct the series of messages. But maybe someone else would like to intervene (I hope so -- that would save me from having to do it all over again).

**Comment by nathanielvirgo** [comment] 2023-12-11 10:01
to be clear, I intended zulip/zulip#29097 to be about the UX issue (when this happens it's not obvious that it's happened or how to recover) and this one to be about the actual bug, which is that when there are too many equations the message cannot be posted.

**Comment by nathanielvirgo** [comment] 2023-12-11 10:05
even if there's intended to be a limit on the number of equations, I *do* think it's a bug that the message reported to the user is "Your message is taking longer than expected to be sent. Sending...". That is simply an incorrect error message.

**Comment by andersk** [comment] 2023-12-11 18:50
> But does 'not planned' mean this isn't considered a bug?

This is just the way GitHub displays issues closed as duplicate. (See the tooltip when you hover it: “Won’t fix, can’t repro, duplicate, stale”.) zulip/zulip#17425 is still open.
