### ISSUE TITLE
Zulip desktop on MacOS Big Sur shows gray screen when new message arrives

### ISSUE THREAD

**Issue by ghost** [zulip/zulip-desktop#1044] opened 2020-11-23 18:01 UTC
**Describe the bug**
When a new message arrives on Zulip Desktop the screen goes gray. Refresh is needed to render page.

**To Reproduce**
Install Zulip Desktop on Big Sur and see problem

**Expected behavior**
Updated screen without need for refresh

**Screenshots**
![image](https://user-images.githubusercontent.com/74922956/99997973-37e93a80-2dbe-11eb-8feb-1b10ea1602e0.png)

**Desktop (please complete the following information):**
 - Operating System: 
MacOS 11.0.1
 - Zulip Desktop Version:
5.4.3

**Comment by andersk** [comment] 2020-11-24 02:33
Duplicate of #1016.

**Closed as completed by andersk** 2020-11-24 02:33 UTC
