### ISSUE TITLE
Copy entire message by selecting it with triple click (Windows)

### ISSUE THREAD

**Issue by hollov** [zulip/zulip-desktop#1071] opened 2021-01-27 14:14 UTC
**Problem Description**
When I select the whole message with triple click and copy it, the name of the user who sent that message AND the next message with user name are also copied to the clipboard
It's quite cumbersome to copy eg. file paths this way; always have to select the text with LMB drag-select.

**Proposed Solution**
Please make it copy just the message itself.

**Comment by ashishbinu** [comment] 2021-03-16 17:22
@hollov I tried this in linux app image version `5.6.0` and seems to be working fine.

**Comment by andersk** [comment] 2022-04-02 05:40
This happens in the server’s web frontend, and is a duplicate of zulip/zulip#18789.

**Closed as completed by andersk** 2022-04-02 05:40 UTC
